final version

diff --git a/.github/workflows/commit-stage--validate-terraform.yml b/.github/workflows/commit-stage--validate-terraform.yml
--- a/.github/workflows/commit-stage--validate-terraform.yml
+++ b/.github/workflows/commit-stage--validate-terraform.yml
@@ -46,16 +46,11 @@ jobs:
         run: |
           terraform init
           terraform plan -detailed-exitcode
-          echo "Exit code is: $?"
-          CODE=$?
-          echo $CODE
           echo "::set-output name=exitcode::$?"
       
       - name: Check Plan Result
         if: steps.plan.outputs.exitcode == '2' || steps.plan.outputs.exitcode == '1'
-        run: exit 1
+        run: |
+          echo "Changes Detected Or Terraform Plan Failed"
+          exit 1
         shell: bash
-      
-      - name: No Changes
-        if: steps.plan.outputs.exitcode == '0'
-        run: echo "No changes detected"
